### ISSUE TITLE
Go to definition (F12) in visual studio 2022 community doesn't work

### ISSUE THREAD

**Issue by chaofine** [AvaloniaUI/AvaloniaVS#436] opened 2024-01-05 05:38 UTC
### Describe the bug

visual studio 2022 community , avalonia for vs 2022 11.5

hello everyone, I want browse source code of avalonia using Ctrl and click (same as F12), it couldn't jump to decompiled source code. but other dotnet built-in class (e.g. System.Threading.Tasks) can. Anyone has same problem?

### To Reproduce

visual studio 2022 community , avalonia for vs 2022 11.5
Ctrl and click or use F12

### AvaloniaVS plugin version

11.5

### Avalonia version

11.0.2

### Visual Studio version

visual studio community 2022 17.5.5

### Relevant log output

```shell
nothing output
```

**Comment by dpieve** [comment] 2024-04-05 13:09
From the .axaml file it is not possible. But I can go to a definition from a .axaml.cs or .cs file. I just press F12 on top of their names. I use VS Community 17.9.5. 
I tried Grid, StackPanel, Point and Colors, all of them are under the namespace Avalonia.
I'm not sure if that's what you meant, but if it is, it works here

**Comment by maxkatz6** [comment] 2024-04-05 22:03
Duplicate of https://github.com/AvaloniaUI/AvaloniaVS/issues/385

**Closed by maxkatz6** 2024-04-05 22:03 UTC
Labels: bug
