### ISSUE TITLE
Avalonia and VS2022

### ISSUE THREAD

**Issue by SaschaSchr** [AvaloniaUI/AvaloniaVS#403] opened 2023-10-12 15:22 UTC
### Describe the bug

There seems to be an issue with this plugin and the latest preview of VS2022. When creating an Avalonia C# project, I get an error "Attempted to access a missing method." The project folder is created, and is empty.

### To Reproduce

I created a new project and the this message comes: "Attempted to access a missing method." 

### AvaloniaVS plugin version

11.4

### Visual Studio version

22 (newest)

### Relevant log output

```shell
I cant create an Avalonia Project.
```

**Comment by Takoooooo** [comment] 2023-10-12 15:58
duplicate of https://github.com/AvaloniaUI/TemplateStudio/issues/20

**Closed as completed by Takoooooo** 2023-10-12 15:58 UTC
Labels: bug
