### ISSUE TITLE
Better filtering for Intellisense completion suggestions

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/AvaloniaVS#235] opened 2022-02-09 03:40 UTC
Currently Intellisense suggestions often suggest things that are completely irrelevant or are "internal" to Avalonia. Biggest offender is typing ContentTemplate, and ContentTemplateResult is the first suggestion. HorizontalContentAlignment and VerticalContentAlignment are always prioritized over HorizontalAlignment and VerticalAlignment - IMO the shorter name properties should be displayed first. These are just a couple that immediately come to mind, there are others though. In both these cases, I think sorting the completion list would solve at least the immediate issue - even if not a great fix overall.

![image](https://user-images.githubusercontent.com/40413319/153116619-974eedcc-e6d5-49db-b527-c225e01fe9c8.png)

Typing a markup extension like {StaticResource } always produces a list of Default/Simple theme resources. It'd be nice if this could not do this, particularly if the Default/Simple theme isn't used. Even better if it could read the current resources available in the current App, or if loading from the entire solution may be a perf problem, at least the current document and App.axaml should be manageable. 

![image](https://user-images.githubusercontent.com/40413319/153117065-d8f37a78-5b87-466e-9f9b-417d5a9643c7.png)

I wanted to try to tackle this myself, but I can't wrap my head around how intellisense works, particularly because its seems it works both here in the extension and the Avalonia IDE submodule, and it's not clear how they link together.

**Comment by FoggyFinder** [comment] 2022-02-10 22:42
Duplicate of: #130

**Closed** 2023-01-03 21:19 UTC
